<?php

namespace App\Service;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;

class ExcelExportService
{
    public function createSpreadsheet(string $title = 'Export'): Spreadsheet
    {
        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setCreator('Little ISMS Helper')
            ->setTitle($title)
            ->setSubject($title)
            ->setDescription('Generated by Little ISMS Helper');

        return $spreadsheet;
    }

    public function addHeaderRow(Spreadsheet $spreadsheet, array $headers, int $row = 1): void
    {
        $sheet = $spreadsheet->getActiveSheet();
        $col = 'A';

        foreach ($headers as $header) {
            $cell = $col . $row;
            $sheet->setCellValue($cell, $header);

            // Style header
            $sheet->getStyle($cell)->applyFromArray([
                'font' => [
                    'bold' => true,
                    'color' => ['rgb' => 'FFFFFF'],
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '4A5568'],
                ],
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                    'vertical' => Alignment::VERTICAL_CENTER,
                ],
            ]);

            $sheet->getColumnDimension($col)->setAutoSize(true);
            $col++;
        }
    }

    public function addDataRows(Spreadsheet $spreadsheet, array $data, int $startRow = 2): void
    {
        $sheet = $spreadsheet->getActiveSheet();
        $row = $startRow;

        foreach ($data as $rowData) {
            $col = 'A';
            foreach ($rowData as $value) {
                // Security: Prevent CSV/Excel Formula Injection (OWASP #3 - Injection)
                $safeValue = $this->sanitizeFormulaInjection($value);
                $sheet->setCellValue($col . $row, $safeValue);
                $col++;
            }
            $row++;
        }

        // Apply zebra striping
        for ($i = $startRow; $i < $row; $i++) {
            if ($i % 2 == 0) {
                $sheet->getStyle('A' . $i . ':' . $col . $i)->applyFromArray([
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => ['rgb' => 'F7FAFC'],
                    ],
                ]);
            }
        }
    }

    public function generateExcel(Spreadsheet $spreadsheet): string
    {
        $writer = new Xlsx($spreadsheet);

        ob_start();
        $writer->save('php://output');
        $content = ob_get_clean();

        return $content;
    }

    public function downloadExcel(Spreadsheet $spreadsheet, string $filename): void
    {
        $content = $this->generateExcel($spreadsheet);

        // Security: Sanitize filename to prevent header injection (OWASP #3 - Injection)
        $safeFilename = preg_replace('/[^\w\s\.\-]/', '', $filename);

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $safeFilename . '"');
        header('Content-Length: ' . strlen($content));

        echo $content;
    }

    public function exportArray(array $data, array $headers, string $sheetName = 'Export'): Spreadsheet
    {
        $spreadsheet = $this->createSpreadsheet($sheetName);
        $spreadsheet->getActiveSheet()->setTitle($sheetName);

        $this->addHeaderRow($spreadsheet, $headers);
        $this->addDataRows($spreadsheet, $data);

        return $spreadsheet;
    }

    /**
     * Security: Prevent CSV/Excel Formula Injection
     *
     * Formula injection occurs when spreadsheet applications interpret cell values
     * starting with =, +, -, @, or tab as formulas. This can lead to:
     * - Remote code execution
     * - Data exfiltration
     * - Local file inclusion
     *
     * @param mixed $value The cell value to sanitize
     * @return string The sanitized value
     */
    private function sanitizeFormulaInjection(mixed $value): string
    {
        // Convert to string
        $value = (string) $value;

        // Check if value starts with dangerous characters
        if (preg_match('/^[\=\+\-\@\t\r]/', $value)) {
            // Prefix with a single quote to force text interpretation
            $value = "'" . $value;
        }

        return $value;
    }
}
